first pass of Github Pages documentation
hyperledger-labs/firefly pull request #50
Opened 2021-06-08 21:58 UTC by nickgaski

2021-06-08 22:03 UTC, nickgaski commented
This will still need to be integrated with GitHub pages.  -> Settings -> Pages -> choose `/docs` as the root source.

2021-06-09 14:18 UTC, nguyer requested changes
Please make sure your commit includes proper sign-off. You can amend the existing commit by running:
```git commit --amend -s```

You may need to force push to your fork after that.

2021-06-09 14:18 UTC, nguyer commented on docs/index.md
> +# Firefly
```suggestion
# FireFly
```

2021-06-09 16:33 UTC, nickgaski commented
rebasing

2021-06-09 20:07 UTC, shorsher commented
closing in favor of https://github.com/hyperledger-labs/firefly/pull/53

2021-06-09 20:07 UTC, closed without merging