Enhance blob upload support, to include metadata
hyperledger-labs/firefly pull request #80
Opened 2021-06-15 21:54 UTC by peterbroadhurst

- Blobs now can have both a `blob` attachment and `value` JSON
- On upload user can add some extra form parameters - must be before the upload file itself:
  - `metadata` - can be a string or a JSON object
  - `autometa` - if `true` then the `filename`,`size` and `mimetype` are added to JSON metadata
     - Can be combined with `metadata` if the metadata is JSON
  - `datatype.name` - if the metadata needs to be validated per a datatype
  - `datatype.version` - if the metadata needs to be validated per a datatype
  - `validator` - to customize the validator (only `json` is supported today)
- The `hash` of the `data` object created, will be one of:
  - The `value` hash - if just a JSON value
  - The `blob` hash reference - if just a BLOB value
  - A hash of the two HEX hashes concatenated together (no spaces or separators)

2021-06-21 14:56 UTC, nguyer commented
FYI @jebonfig this PR will require a new field added to the config to enable the UI:
```yaml
ui:
  enabled: true
```

2021-06-21 15:57 UTC, nguyer requested changes
One thing to check in the migrations, otherwise looks good.

2021-06-21 17:13 UTC, peterbroadhurst commented on db/migrations/ql/000022_create_blobs_table.up.sql
> +  peer           string
Thanks @nguyer - this should be `NOT NULL` - I'll add a fix to that in #91

2021-06-22 13:21 UTC, nguyer approved these changes

2021-06-22 13:21 UTC, nguyer commented
Marking approved, as the one issue I raised is fixed in the next PR

2021-06-22 13:24 UTC, merged

2021-07-01 13:31 UTC, peterbroadhurst commented
Fixes https://github.com/hyperledger-labs/firefly/issues/77